global:
    scrape_interval: 5s
    evaluation_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['yourip:9090']
    metrics_path: "/metrics"
  
  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
         - targets: ['yourip:9100']
    metrics_path: "/metrics"